---
- name: CONFIGURE CISCO SWITCH PORT
  hosts: '{{ tower_inventory_cisco }}'
  connection: network_cli
  gather_facts: no

  vars:
    interface_name: GigabitEthernet1/0
    access_vlan: 20
    port_enabled: false


  tasks:
    
     - name: CONFIGURE AND ENABLE L2 PORT
       block: 
       
         - name: CONFIUGRE L2 PORT
           ios_l2_interface:
             name: "{{ interface_name }}"
             desription: 'Configured by Ansible'
             mode: access
             native_vlan: 20

         - name: ENABLE L2 PORT
           ios_config:
             lines:
               - NO SHUTDOWN
           parents: interface  "{{ interface_name }}"

       when: port_enabled


     - name: DISABLE L2 PORT
       ios_config:
         lines:
           - SHUTDOWN
         parents: interface  "{{ interface_name }}"
       when: not port_enabled

