---
- name: Linux OS Hardening
  hosts: '{{ tower_inventory }}'
  gather_facts: true


  tasks:
    - include_role:
         name: dev-sec.os-hardening
      when: server_os == 'RedHat'
    
    
    
    
    
    
    
    