---
- name: INSTALL IIS WEB SERVER
  hosts: '{{ tower_inventory }}'
  gather_facts: false


  tasks:
    - include_role: 
         name: iis_install
      when: server_os == 'windows'

  


      
    

    

  
    