---
- name:  CREATE NEW LINUX USER
  hosts: "{{ tower_inventory }}"
  gather_facts: yes

  vars:
     linux_server: all

  tasks: 
    - name: ADD NEW USER
      user:
        name: "{{ server_username }}"
        shell: /bin/bash
        password: "{{ user_password }}"
        groups: 
          - developers
          - wheel
        append: yes
      when:  server_os == 'linux'
    

    