---
- name: Linux OS Hardening
  hosts: '{{ tower_inventory }}'
  gather_facts: false


  tasks:
    - include_role:
         name: dev-sec.os-hardening
      when: server_os == 'linux'
    
    
    
    
    
    
    
    