---
- name: Set Windows Security Policies
  hosts: '{{ tower_inventory }}'
  gather_facts: false
  

  
  tasks:

    - set_fact:
        run_report: true
      when: server_os == 'windows'
      
    - include_role:
        name: '{{ item }}'
      with_items:
         - max_password_age 
         - system_events
      when: server_os == 'windows'

    